data:
  mesh_dir: /home/nshah/work/projects/transfer/scratch/data/input/meshes/emotional_body/fancy_dance
  batch_size: 128

model:
  n_betas: 300
  gender: male
  path: /home/nshah/work/models/supr/supr_male.npy

experiment:

  optimizer_params:
    lr: 0.1
    max_iter: 50
    line_search_fn: strong_wolfe

  optimization:
    n_iters: 500
    low_loss_threshold: 2.0e-3
    low_loss_delta_threshold: 1.0e-6
    n_consecutive_low_loss_delta_iters_threshold: 5
    vertex_loss_reduction: mean
    apply_rotation_angles_correction: True

  edge_loss_optimization: 
    use: False
    n_iters: 100
    low_loss_threshold: 0.001
    low_loss_delta_threshold: 0.00001
    n_consecutive_low_loss_delta_iters_threshold: 5
    apply_rotation_angles_correction: True

  separate_global_translation_optimization: 
    use: True
    n_iters: 50
    low_loss_threshold: 2.0e-2
    low_loss_delta_threshold: 1.0e-4
    n_consecutive_low_loss_delta_iters_threshold: 5
    vertex_loss_reduction: mean

  single_betas_optimization: False
  inherit_prev_batch_params_during_optimization: False
  vertex_to_vertex_loss_type: v2v_error

device: cuda:0
out_dir: /home/nshah/work/projects/transfer/scratch/data/output/emotional_body/fancy_dance/run5
save_output_meshes: True
log_iterations_interval: 10
